### ISSUE TITLE
Doesn't create .npmrc files

### ISSUE THREAD

**Issue by josiahsprague** [SparkartGroupInc/slush-solidus#4]
Our current setup with docker-solidus relies on `.npmrc` files in the site's repo. For some reason, even though the `.npmrc` file exists in the template, it's not being cloned on `slush solidus`. This might be related to the issue here: https://github.com/gulpjs/gulp/issues/1523

**Comment by josiahsprague** [comment]
Judging by the info here: https://docs.npmjs.com/files/npmrc#files

We might have to manually create an `.npmrc` file after initializing a new repo, and manually set permissions to `0600` before running `npm install`. I'm surprised we haven't run into any issues with this before now. cc @joanniclaborde @pushred

**Comment by joanniclaborde** [comment]
Have you tried setting an `NPM_TOKEN` env variable before running your script?

**Comment by josiahsprague** [comment]
The issue was that `npm i -g ./slush-solidus` was skipping `.npmrc`, so by the time `slush solidus` was run, that file was already missing. Fixed by https://github.com/SparkartGroupInc/slush-solidus/commit/4674837a592563a8cd09a6c4d3c980961e4d0d95
